#!/usr/bin/with-contenv bash

cat <<EOF
---
dracula Theme Installer
Source: https://github.com/dracula/qbittorrent
---
EOF


if [ ! -d /dracula ]; then
  echo "Running installer..."

  curl -o dracula.zip  https://github.com/dracula/qbittorrent/archive/refs/heads/master.zip &&
    unzip dracula.zip -d /

  # Remove zip after unpacking
  rm /dracula.zip

  mv /qbittorrent-mast* /dracula

  echo "Done! The theme is installed in the root folder. Apply it from WEBUI settings."
else
  echo "dracula theme is already installed. Exiting..."
fi
